Devil/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import view
from . import search
from . import searchpost
from . import home

urlpatterns = [
    url(r'^hello$', view.hello),
    url(r'^admin/', admin.site.urls),
    url(r'^search-form$', search.search_form),
    url(r'^search$', search.search),
    url(r'^search-post$', searchpost.search_post),
    url(r'^home$', home.home),
    url(r'^blog/', include('MyModel.urls', namespace='blog')),
]

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MyModel/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url(r'^edit/action/$', views.edit_action, name='edit_action'),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
]

MyModel/models.py
from django.db import models


# Create your models here.
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)  # 博客题目
    category = models.CharField(max_length=50, blank=True)  # 博客标签
    date_time = models.DateTimeField(auto_now_add=True)  # 博客日期
    content = models.TextField(blank=True, null=True)  # 博客文章正文

    # python2使用__unicode__, python3使用__str__  admin显示的文字
    def __str__(self):
        return self.title

    class Meta:  # 按时间下降排序
        ordering = ['-date_time']

MyModel/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse
from . import models


# Create your views here.

def index(request):
    articles = models.Article.objects.all()
    return render(request, 'MyModel/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'MyModel/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'MyModel/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'MyModel/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'Title')
    content = request.POST.get('content', 'Content')
    category = request.POST.get('category', 'Category')
    article_id = request.POST.get('article_id', '0')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content, category=category)
    else:
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.category = category
        article.save()
    # articles = models.Article.objects.all()
    # return render(request, 'MyModel/index.html', {'articles': articles})
    # articles = models.Article.objects.all()
    return HttpResponseRedirect('/blog/index')

MyModel/templates/MyModel/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/>
<a href="{% url 'blog:edit_page' article.id %}">文章修改</a>
</body>
</html>

MyModel/templates/MyModel/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.id|default:'0' }}">
    <label>文章标题
        <input type="text" name="title" value="{{ article.title }}"/>
    </label>
    <br/>
    <label>标签
        <input type="text" name="category" value="{{ article.category }}"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="content" value="{{ article.content }}"/>
    </label>
    <br/>
    <input type="submit" value="提交">
</form>
</body>
</html>

MyModel/templates/MyModel/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>抠脚奇</title>
</head>
<body>
<p1 style="font-size:100px" >
    抠脚哟奇奇
</p1>
</body>
</html>

MyModel/templates/MyModel/homepage.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    {% load static %}
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            float: left;
        }
    </style>
</head>
{% load static %}
<body>
<h1>你好，世界！</h1>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static '/js/bootstrap.min.js' %}"></script>
<div><img src="{% static '/img/mainpic/logo.png' %}" width="200" align="center">南昌山特矿业机械配件有限公司</div>
<div>联系电话：2313123123</div>
<p style="text-indent:2em;">
    南昌山特矿业机械配件有限公司成立于2016年，注册资金500万元，是一家专业从事矿业机械配件的贸易公司，总部设立于南昌市三星大厦B座803室。公司主要销售产品为：各种型号全液压履带式及轮式挖掘机的耐磨配件（斗齿、挖斗、齿座、刀角板、护板、护块、装载机铲齿、松土齿、销子卡环、螺栓螺母、轮一带、加长臂、销轴等）系列配件。面对激烈的市场竞争，公司正凭借其自身的优势，整合外部资源，优化内部管理，不断开拓创新，朝着业务专业化、经营多元化的方向阔步前进。
    <br/>&nbsp;&nbsp;&nbsp;&nbsp;本公司秉承品质与服务的经营理念，竭诚为新老客户提供优质产品与服务，最大限度满足广大客户的需求。服务客户，成就客户，“开拓创新，追求卓越”是南昌山特的不断追求，真诚期待与新老客户合作并进，共创未来!
    我们将不断融合久益的先进技术和管理经验，努力为广大客户生产“零烦恼”的产品，提供高品质的服务，我们期待与你们携手合作，共创美好明天!
    <br/>&nbsp;&nbsp;&nbsp;&nbsp; 公司核心文化
    <br/> 　&nbsp;&nbsp;&nbsp;&nbsp;1、企业远景：以振兴民族工业为己任，打造国际知名品牌。
    <br/> 　&nbsp;&nbsp;&nbsp;&nbsp;2、企业使命：时刻为用户提供最完美的电气柜体结构及控制系统。
    <br/> 　&nbsp;&nbsp;&nbsp;&nbsp;3、企业价值观：成就客户、创造价值、为世界添彩。
    <br/> 　&nbsp;&nbsp;&nbsp;&nbsp;4、企业宗旨：一流管理、一流技术、一流产品、一流服务。
    <br/> 　&nbsp;&nbsp;&nbsp;&nbsp;5、企业作风：和谐、诚信、高效、创新。
    <br/> 　&nbsp;&nbsp;&nbsp;&nbsp;6、企业战略：技术现代化、市场多元化、生产精心化、管理科学化。
    <br/> 　&nbsp;&nbsp;&nbsp;&nbsp;7、用人原则：人品第一、能力第二。
    <br/> 　&nbsp;&nbsp;&nbsp;&nbsp;8、管理理念：以人为本、坚持原则。
    <br/> 　&nbsp;&nbsp;&nbsp;&nbsp;9、市场理念：没有打不进去的市场，没有沟通不了的客户。
    <br/>
</p>
</body>
</html>

MyModel/templates/MyModel/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的博客</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">编写新文章</a>
</h1>

{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br>
{% endfor %}
</body>
</html>

MyModel/templates/MyModel/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        post
    </title>
</head>
<body>
<form action="/search-post" method="post">
    {% csrf_token %}
    <input type="text" name="q">
    <input type="submit" value="Submit">
</form>

<p>{{ rlt }}</p>

</body>
</html>

MyModel/templates/MyModel/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索</title>
</head>
<body>
<form action="/search" method="get">
    <input type="text" name="q">
    <input type="submit" value="搜索">
</form>
</body>
</html>